version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - static_db:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: palexey/api_yamdb:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/

    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
  
    ports:
      - "80:80"
  
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

      - static_value:/var/html/static/

      - media_value:/var/html/media/

      - ../../etc/letsencrypt/live/simplicatus.hopto.org/fullchain.pem:/etc/letsencrypt/live/simplicatus.hopto.org/fullchain.pem
      - ../../etc/letsencrypt/live/simplicatus.hopto.org/privkey.pem:/etc/letsencrypt/live/simplicatus.hopto.org/privkey.pem
      - ../../etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ../../etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem

    depends_on:
      - web

volumes:
  static_db:
  static_value:
  media_value:
